version: "3.6"
services:
  postgres-auth:
    image: postgres:latest
    restart: unless-stopped
  postgres-resturant:
    image: postgres:latest
    restart: unless-stopped
  postgres-order:
    image: postgres:latest
    restart: unless-stopped
  postgres-admin:
    image: postgres:latest
    restart: unless-stopped
  
  auth-service:
    build:
      context: ./app/auth-service
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    env_file:
      - ./apps/auth-service/.env
 