version: "3.6"
services:
  postgres-auth:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="auth-api","auth-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - auth_api_data:/data/postgres
    ports:
      - 5431:5432
  postgres-resturant:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="restaurant-api","restaurant-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - restaurant_api_data:/data/postgres
    ports:
      - 5432:5432
volumes:
  auth_api_data: {}
  restaurant_api_data: {}
