version: "3.6"
services:
 
 gateway-service:
    build:
      context: ./apps/gateway-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./apps/gateway-service/.env 