version: "3.6"
services:
  postgres-auth:
    image: postgres:latest
    restart: unless-stopped
  postgres-home-manager:
    image: postgres:latest
    restart: unless-stopped
  postgres-booking-manager:
    image: postgres:latest
    restart: unless-stopped