version: "3.6"
services:
  postgres-auth:
    image: postgres:latest
    restart: unless-stopped
  postgres-resturant:
    image: postgres:latest
    restart: unless-stopped
  postgres-order:
    image: postgres:latest
    restart: unless-stopped

 