version: "3.6"
services:
  restaurant-service:
    build:
      context: ./apps/restaurant-service
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    env_file:
      - ./apps/restaurant-service/.env

volumes:
  auth_api_data: {}
  restaurant_api_data: {}
  order_api_data: {}
  admin_api_data: {}
