version: "3.6"
services:
  postgres-auth:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="auth-api","auth-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - auth_api_data:/data/postgres
    ports:
      - 5431:5432
  postgres-resturant:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="restaurant-api","restaurant-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - restaurant_api_data:/data/postgres
    ports:
      - 5432:5432
  postgres-order:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="order-api","order-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - order_api_data:/data/postgres
    ports:
      - 5433:5432
  postgres-admin:
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=development_pass
      - POSTGRES_MULTIPLE_DATABASES="admin-api","admin-api-testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - admin_api_data:/data/postgres
    ports:
      - 5434:5432

  auth-service:
    build:
      context: ./apps/auth-service
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    env_file:
      - ./apps/auth-service/.env
  restaurant-service:
    build:
      context: ./apps/restaurant-service
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    env_file:
      - ./apps/restaurant-service/.env
  order-service:
    build:
      context: ./apps/order-service
      dockerfile: Dockerfile
    ports:
      - 5003:5003
    env_file:
      - ./apps/order-service/.env  
  admin-service:
    build:
      context: ./apps/admin-service
      dockerfile: Dockerfile
    ports:
      - 5004:5004
    env_file:
      - ./apps/admin-service/.env
volumes:
  auth_api_data: {}
  restaurant_api_data: {}
  order_api_data: {}
  admin_api_data: {}
