version: "3.6"
services:

   admin-service:
    build:
      context: ./apps/admin-service
      dockerfile: Dockerfile
    ports:
      - 5004:5004
    env_file:
      - ./apps/admin-service/.env 

 
  